version: '3'
services:
    client:
        build: ./client/
        environment:
        - ZMQ_PUB_ADDRESS=tcp://server:3000
    server:
        build: ./server/
        ports:
        - 3000:3000
        environment:
        - ZMQ_BIND_ADDRESS=tcp://*:3000